name: check
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Run plugin verifier
        run: ./gradlew runPluginVerifier

      - uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/distributions/*.zip
          retention-days: 10
