name: publish
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Run plugin verifier
        run: ./gradlew runPluginVerifier

      - uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/distributions/*.zip
          retention-days: 10

      - name: Publish plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin
